"""add research threads and messages

Revision ID: 006e277d1355
Revises: aa65641f98df
Create Date: 2026-04-25 18:01:42.981206

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '006e277d1355'
down_revision: str | Sequence[str] | None = 'aa65641f98df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f("ix_research_threads_id"), "research_threads", ["id"], unique=False
    )
    op.create_table('research_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['research_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f("ix_research_messages_id"), "research_messages", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_messages_id'), table_name='research_messages')
    op.drop_table('research_messages')
    op.drop_index(op.f('ix_research_threads_id'), table_name='research_threads')
    op.drop_table('research_threads')
    # ### end Alembic commands ###
